from __future__ import annotations
import json
from pathlib import Path
from flaas.osc_rpc import OscTarget
from flaas.device_set_param import device_set_param


def eq8_set(
    track_id: int,
    device_id: int,
    band: int,
    side: str,
    param: str,
    value: float,
    target: OscTarget = OscTarget(),
    timeout_sec: float = 5.0,
    dry: bool = False,
) -> None:
    """
    Set EQ Eight parameter using semantic path (band/side/param).
    
    Requires map file: data/registry/eq8_map_t{track_id}_d{device_id}.json
    Generated by: flaas eq8-map <track_id> <device_id>
    
    Resolves semantic name to param_id, then calls device_set_param.
    """
    map_path = Path(f"data/registry/eq8_map_t{track_id}_d{device_id}.json")
    
    if not map_path.exists():
        print(f"ERROR: Map file not found: {map_path}")
        print(f"Run this first: flaas eq8-map {track_id} {device_id}")
        raise SystemExit(1)
    
    map_data = json.loads(map_path.read_text(encoding="utf-8"))
    
    try:
        param_id = map_data["groups"]["bands"][str(band)][side][param]
    except KeyError as e:
        print(f"ERROR: Invalid semantic path: band={band} side={side} param={param}")
        print(f"KeyError: {e}")
        print(f"Valid bands: 1-8, sides: A/B, params: on|type|freq|gain|res")
        raise SystemExit(1)
    
    device_set_param(
        track_id=track_id,
        device_id=device_id,
        param_id=param_id,
        value=value,
        target=target,
        timeout_sec=timeout_sec,
        dry=dry,
    )
