from __future__ import annotations
from pathlib import Path
from flaas.osc_rpc import OscTarget
from flaas.eq8_set import eq8_set


def eq8_reset_gains(
    track_id: int,
    device_id: int,
    target: OscTarget = OscTarget(),
    timeout_sec: float = 5.0,
    dry: bool = False,
) -> None:
    """
    Reset all EQ Eight band gains (A and B, bands 1-8) to 0.0 dB.
    
    Requires map file: data/registry/eq8_map_t{track_id}_d{device_id}.json
    Generated by: flaas eq8-map <track_id> <device_id>
    
    Calls eq8_set for each band/side combination, fail-fast on error.
    """
    map_path = Path(f"data/registry/eq8_map_t{track_id}_d{device_id}.json")
    
    if not map_path.exists():
        print(f"ERROR: Map file not found: {map_path}")
        print(f"Run this first: flaas eq8-map {track_id} {device_id}")
        raise SystemExit(1)
    
    for band in range(1, 9):
        for side in ["A", "B"]:
            eq8_set(
                track_id=track_id,
                device_id=device_id,
                band=band,
                side=side,
                param="gain",
                value=0.0,
                target=target,
                timeout_sec=timeout_sec,
                dry=dry,
            )
    
    print(f"DONE eq8-reset-gains track_id={track_id} device_id={device_id} dry={dry}")
