from __future__ import annotations
import json
from pathlib import Path
from flaas.osc_rpc import OscTarget
from flaas.device_set_param import device_set_param


LIMITER_PARAM_NAMES = {
    "gain": "Gain",
    "ceiling": "Ceiling",
    "release": "Release time",
    "auto": "Auto",
    "link": "Link Channels",
    "lookahead": "Lookahead",
}


def limiter_set(
    track_id: int,
    device_id: int,
    param: str,
    value: float,
    target: OscTarget = OscTarget(),
    timeout_sec: float = 5.0,
    dry: bool = False,
) -> None:
    """
    Set Limiter parameter using semantic name.
    
    Requires map file: data/registry/device_map_t{track_id}_d{device_id}.json
    Generated by: flaas device-map <track_id> <device_id>
    
    Resolves semantic name to param_id via name matching, then calls device_set_param.
    """
    map_path = Path(f"data/registry/device_map_t{track_id}_d{device_id}.json")
    
    if not map_path.exists():
        print(f"ERROR: Map file not found: {map_path}")
        print(f"Run this first: flaas device-map {track_id} {device_id}")
        raise SystemExit(1)
    
    map_data = json.loads(map_path.read_text(encoding="utf-8"))
    
    expected_name = LIMITER_PARAM_NAMES.get(param)
    if not expected_name:
        print(f"ERROR: Unknown param '{param}'")
        print(f"Valid params: {', '.join(LIMITER_PARAM_NAMES.keys())}")
        raise SystemExit(1)
    
    param_id = None
    for p in map_data["params"]:
        if p["name"] == expected_name:
            param_id = p["id"]
            break
    
    if param_id is None:
        print(f"ERROR: Parameter '{expected_name}' not found in device map")
        print(f"Device class: {map_data.get('device_class_name', 'unknown')}")
        raise SystemExit(1)
    
    device_set_param(
        track_id=track_id,
        device_id=device_id,
        param_id=param_id,
        value=value,
        target=target,
        timeout_sec=timeout_sec,
        dry=dry,
    )
